sudo: required

language: generic

services:
        - docker

before_install:
        - docker build -t vikumca/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true vikumca/react-test npm test -- --coverage

after_success:
        - docker build -t vikumca/multi-client ./client
        - docker build -t vikumca/multi-nginx ./nginx
        - docker build -t vikumca/multi-server ./server
        - docker build -t vikumca/multi-worker ./worker  

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

        - docker push vikumca/multi-client
        - docker push vikumca/multi-nginx
        - docker push vikumca/multi-server
        - docker push vikumca/multi-worker  

deploy:
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        edge: true
        provider: elasticbeanstalk
        region: ap-south-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-ap-south-1-278126853435
        bucket_path: docker-multi
        skip_cleanup: true
        on:
                branch: master

