sudo: required

language: generic

services:
        - docker

before_install:
        - docker build -t vikumca/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true vikumca/react-test npm test

after_success:
        - docker build -t vikumca/multi-client ./client
        - docker build -t vikumca/multi-nginx ./nginx
        - docker build -t vikumca/multi-server ./server
        - docker build -t vikumca/multi-worker ./worker  

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

        - docker push vikumca/multi-client
        - docker push vikumca/multi-nginx
        - docker push vikumca/multi-server
        - docker push vikumca/multi-worker  

